- name: Install Fish shell
  become: true
  package:
    state: present
    name: "fish"

- name: Switch default shell to fish
  become: true
  user:
    name: "{{ ansible_user }}"
    shell: "/usr/bin/fish"

- name: Download Starship Shell prompt install script
  get_url:
    url: "https://starship.rs/install.sh"
    dest: "/tmp/install.sh"

- name: Install Starship
  become: true
  shell: "bash /tmp/install.sh -y"
  ignore_errors: true

- name: Set up ~/.config/starship.toml
  copy:
    src: "starship.toml"
    dest: "~/.config/starship.toml"

- name: Set up ~/.config/fish/config.fish
  lineinfile:
    create: true
    path: "~/.config/fish/config.fish"
    line: "{{ item }}"
  with_items:
    - "starship init fish | source"
    - "abbr -a -- - 'cd -'"
    - "alias cat='bat'"
    - "alias find='echo you should use fd instead'"
    - "alias diff='icdiff'"
    - "alias top='htop'"
    - "alias du='ncdu'"
    - "alias grep='echo you should use rg instead'"
    - "alias watch='echo you should use entr instead'"
    - "alias vim='nvim'"
    - "set PATH $PATH $HOME/.local/bin"
    - "set EDITOR nvim"
    - "set VISUAL nvim"
