- name: Install KVM (Debian)
  when: ansible_os_family == "Debian"
  become: true
  package:
    state: present
    name: "{{ item }}"
  with_items:
    - "qemu-kvm"
    - "libvirt-clients"
    - "libvirt-daemon-system"
    - "bridge-utils"
    - "virt-viewer"
    - "virt-manager"

- name: Add user to libvirt group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: "libvirt"
    append: true

