---
language: python
before_install:
  - "sudo apt update -qq"
install:
  - "sudo apt install python3-apt"
  - "pip install ansible"
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"
script:
  - "ansible-playbook -v pc.yml"
