---
sudo: required
env:
  - distro_name: ubuntu
    distro_tag: 16.04
  - distro_name: debian
    distro_tag: 8
  - distro_name: centos
    distro_tag: 7
services:
  - docker
before_install:
  - 'docker pull ${distro_name}:${distro_tag}'
script:
