---
sudo: required
env:
  - repo: geerlingguy
    distro_name: ubuntu1604
  - repo: geerlingguy
    distro_name: debian8
  - repo: geerlingguy
    distro_name: centos7
services:
  - docker
before_install:
  - 'docker pull ${repo}/docker-${distro_name}-ansible'
script:
  - container_id=$(mktemp)
  - 'docker run --detach --volume="${PWD}/roles/vim":/etc/ansible/roles/role_under_test:ro --entrypoint "/bin/sh" -it "${repo}/docker-${distro_name}-ansible" > "${container_id}"'
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/role_under_test/tests/main.yml --syntax-check'
