---
sudo: required
env:
  - repo: geerlingguy
    distro_name: ubuntu
    distro_tag: 16.04
  - repo: geerlingguy
    distro_name: debian
    distro_tag: 8
  - repo: geerlingguy
    distro_name: centos
    distro_tag: 7
services:
  - docker
before_install:
  - 'docker pull ${repo}/docker-${distro_name}${distro_tag}-ansible'
script:
  - container_id=$(mktemp)
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/vim:ro --entrypoint "/bin/sh" -it "${repo}/docker-${distro_name}${distro_tag}-ansible" > "${container_id}"'
  - 'docker exec "$(cat ${container_id})" ansible-playbook /etc/ansible/roles/vim/tests/main.yml --syntax-check'
