---
sudo: required
env:
  - distro:
    name: ubuntu
    tag: 16.04
  - distro:
    name: debian
    tag: 8
  - distro:
    name: centos
    tag: 7
services:
  - docker
before_install:
  - 'docker pull ${distro.name}:${distro.tag}'
script:
