---
language: python
before_install:
  - "sudo apt update -qq"
install:
  - "pip install ansible"
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"
script:
  - "ansible-playbook pc.yml --syntax-check"
