---
sudo: required
env:
  - distro_name: ubuntu
    distro_tag: 16.04
  - distro_name: debian
    distro_tag: 8
  - distro_name: centos
    distro_tag: 7
services:
  - docker
before_install:
  - 'docker pull ${distro_name}:${distro_tag}'
script:
  - container_id=$(mktemp)
  - 'docker run --detach --volume="${PWD}":/etc/ansible/roles/vim:ro "${distro_name}:${distro_tag}" > "${container_id}"'
  - >
    docker exec "$(cat ${container_id})"
    ansible-playbook /etc/ansible/roles/vim/tests/main.yml --syntax-check
