---
language: python
version: "2.7"
before_install:
  - "sudo apt update -qq"
  - "sudo apt install python-apt"
install:
  - "pip install ansible"
  - "printf '[defaults]\nroles_path = ../' > ansible.cfg"
script:
  - "ansible-playbook -v pc.yml"
