---
- hosts: localhost 
  tasks:
    - name: Upgrade packages to latest version (Debian)
      when: ansible_os_family == "Debian"
      become: true
      apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: true

    - name: Upgrade packages to latest version (Arch)
      when: ansible_os_family == "Arch"
      become: true
      pacman:
        update_cache: yes
        upgrade: yes

    - name: Install common packages
      become: true
      package:
        state: present
        name: "{{ packages }}"
      vars:
        packages:
        - "coreutils"
        - "htop"
        - "ncdu"
        - "ack"
        - "pandoc"
        - "wireshark-qt"
        - "gparted"
        - "xfce4-terminal"
        - "imagemagick"
        - "openconnect"
        - "keepassxc"
        - "tor"

    - name: Install Debian-only packages
      when: ansible_os_family == "Debian"
      become: true
      package:
        state: present
        name: "{{ packages }}"
      vars:
        packages:
        - "apt-transport-https"
        - "gnome-tweak-tool"
        - "icdiff"
        - "vrms"
        - "entr"
        - "ddd"

    - name: Install Arch-only packages
      when: ansible_os_family == "Arch"
      become: true
      package:
        state: present
        name: "{{ packages }}"
      vars:
        packages:
        - "yaourt"
        - "package-query"

    - name: Install git
      include: git.yml

    - name: Install vim
      include: vim.yml

    - name: Install tmux
      include: tmux.yml

    - name: Install bat
      include: bat.yml

    - name: Install fd
      include: fd.yml

    - name: Install fzf
      include: fzf.yml

    - name: Install Tor browser
      include: tor-browser.yml

    - name: Install Docker
      include: docker.yml

    - name: Install KVM
      include: kvm.yml

    - name: Uninstall and remove unneeded packages from cache
      when: ansible_os_family == "Debian"
      become: true
      apt:
        autoremove: true
        autoclean: true

    - name: Configure .bashrc
      include: bashrc.yml

    - name: Configure aliases
      lineinfile:
        path: "~/.bash_aliases"
        line: "{{ item }}"
      loop:
        - "alias diff='icdiff'"
        - "alias top='htop'"
        - "alias du='ncdu'"
        - "alias grep='echo you should use ack instead'"
        - "alias watch='echo you should use entr instead'"
