- name: Install fd, find replacement (Debian)
  when: ansible_os_family == "Debian"
  become: true
  package:
    state: present
    deb: "https://github.com/sharkdp/fd/releases/download/v7.2.0/fd_7.2.0_amd64.deb"

- name: Install fd, find replacement (Archlinux)
  when: ansible_os_family == "Archlinux"
  become: true
  package:
    state: present
    name: "fd"

- name: Configure alias
  lineinfile:
    create: true
    path: "~/.bash_aliases"
    line: "alias find='echo you should use fd instead'"
