- name: Install Firefox
  become: true
  package:
    state: present
    name: "firefox" 

- name: Find Firefox Profile directory
  find:
    paths: "~/.mozilla/firefox"
    patterns: "*.default"
    file_type: "directory"
  register: profile_directory

- name: Apply Firefox config
  lineinfile:
    create: true
    path: "{{ profile_directory.files[0].path }}/user.js"
    line: "{{ item }}"
  loop:
    - 'user_pref("browser.search.defaultenginename", "DuckDuckGo");'
    - 'user_pref("browser.search.defaulturl", "https://start.duckduckgo.com/?kae=d&kak=-1&kal=-1&kao=-1&kaq=-1&kav=1&kn=1&kam=osm&kax=-1&kap=-1&kau=-1&kt=p&kai=1&q=");'
    - 'user_pref("keyword.URL", "https://start.duckduckgo.com/?kae=d&kak=-1&kal=-1&kao=-1&kaq=-1&kav=1&kn=1&kam=osm&kax=-1&kap=-1&kau=-1&kt=p&kai=1&q=!+");'
    - 'user_pref("privacy.firstparty.isolate", true);'
    - 'user_pref("privacy.resistFingerprinting", true);'
    - 'user_pref("privacy.trackingprotection.enabled", true);'
    - 'user_pref("browser.cache.offline.enable", false);'
    - 'user_pref("browser.safebrowsing.malware.enabled", false);'
    - 'user_pref("browser.safebrowsing.phishing.enabled", false);'
    - 'user_pref("browser.send_pings", false);'
    - 'user_pref("browser.sessionstore.max_tabs_undo", 0);'
    - 'user_pref("browser.urlbar.speculativeConnect.enabled", false);'
    - 'user_pref("dom.battery.enabled", false);'
    - 'user_pref("dom.event.clipboardevents.enabled", false);'
    - 'user_pref("geo.enabled", false);'
    - 'user_pref("media.eme.enabled", false);'
    - 'user_pref("media.gmp-widevinecdm.enabled", false);'
    - 'user_pref("media.navigator.enabled", false);'
    - 'user_pref("network.cookie.cookieBehavior", 1);'
    - 'user_pref("network.cookie.lifetimePolicy", 2);'
    - 'user_pref("network.http.referer.trimmingPolicy", 2);'
    - 'user_pref("network.http.referer.XOriginPolicy", 2);'
    - 'user_pref("network.http.referer.XOriginTrimmingPolicy", 2);'
    - 'user_pref("webgl.disabled", true);'
    - 'user_pref("browser.sessionstore.privacy_level", 2);'
    - 'user_pref("network.IDN_show_punycode", true);'
    - 'user_pref("extensions.blocklist.url", "https://blocklists.settings.services.mozilla.com/v1/blocklist/3/%20/%20/");'
    - 'user_pref("media.peerconnection.enabled", false);'
    - 'user_pref("media.peerconnection.turn.disable", true);'
    - 'user_pref("media.peerconnection.use_document_iceservers", false);'
    - 'user_pref("media.peerconnection.video.enabled", false);'
    - 'user_pref("media.peerconnection.identity.timeout", 1);'
