- name: Install git
  become: true
  package:
    state: present
    name: "git"

- name: Configure git
  git_config:
    name: "credential.helper"
    scope: "global"
    value: "cache --timeout=600"
