- name: Install XFCE stuff
  become: true
  package:
    state: present
    name: "{{ packages }}"
  vars:
    packages:
    - "xfce4"
    - "task-xfce-desktop"

- name: Turn off infuriating beeps
  shell: "xset b off"
