- name: Ensure key present (Necessary for Debian)
  become: true
  apt_key:
    keyserver: keyserver.ubuntu.com
    id: 3653E21064B19D134466702E43D5C49532CBA1A9

- name: Add Yubikey PPA
  become: true
  when: ansible_os_family == "Debian"
  ignore_errors: true
  apt_repository:
    state: present
    repo: "deb http://ppa.launchpad.net/yubico/stable/ubuntu disco main"

- name: Install Yubikey Manager
  become: true
  package:
    state: present
    name: "yubikey-manager"
