- name: Create plugin directory
  file:
    state: "directory"
    path: "~/.local/share/nvim/site/autoload/"

- name: Download vim-plug
  get_url:
    url: "https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim"
    dest: "~/.local/share/nvim/site/autoload/plug.vim"
