- name: Install packages for ProtonVPN
  become: true
  package:
    state: present
    name: "{{ packages }}"
  vars:
    packages:
    - "openvpn"
    - "resolvconf"
    - "network-manager-openvpn"
    - "network-manager-openvpn-gnome"
