- name: Install packages for ProtonVPN
  become: true
  package:
    state: present
    name: "{{ item }}"
  with_items:
    - "openvpn"
    - "resolvconf"

- name: Install network manager package (non-Arch)
  when: ansible_os_family != "Archlinux"
  become: true
  package:
    state: present
    name: "network-manager-openvpn"

- name: Install convenience package for Gnome systems
  when: ansible_env['XDG_CURRENT_DESKTOP'] == "GNOME"
  become: true
  package:
    state: present
    name: "network-manager-openvpn-gnome"
