- name: Install Nextcloud (Debian-based)
  when: ansible_os_family == "Debian"
  include: nextcloud_debian.yml

- name: Install Nextcloud (Solus)
  when: ansible_os_family == "Solus"
  include: nextcloud_solus.yml
