- name: Install Git
  when: ansible_os_family != "Solus"
  include: git.yml

- name: Install Git (Solus)
  when: ansible_os_family == "Solus"
  include: git_solus.yml

- name: Configure git
  git_config:
    name: "credential.helper"
    scope: "global"
    value: "cache --timeout=600"
