- name: Install Yubikey Manager (Debian-based)
  when: ansible_os_family == "Debian"
  include: yubikey_debian.yml

- name: Install Yubikey Manager (Archlinux)
  when: ansible_os_family == "Archlinux"
  include: yubikey_arch.yml

- name: Install Yubikey Manager (Solus)
  when: ansible_os_family == "Solus"
  include: yubikey_solus.yml
