- name: Download Keybase .deb
  get_url:
    url: "https://prerelease.keybase.io/keybase_amd64.deb"
    dest: "/tmp/keybase.deb"

- name: Start .deb install
  become: true
  shell: 'dpkg -i /tmp/keybase.deb'
  ignore_errors: true

- name: Finish installation
  become: true
  shell: 'apt install -f -y'
