- name: Install Docker (Debian-based)
  when: ansible_os_family == "Debian"
  include: docker_debian.yml

- name: Install Docker (Arch-based)
  when: ansible_os_family == "Archlinux"
  include: docker_arch.yml

- name: Install Docker (Solus)
  when: ansible_os_family == "Solus"
  include: docker_solus.yml

- name: Add user to docker group
  become: true
  user:
    name: "{{ ansible_user }}"
    groups: "docker"
    append: true
