- name: Install VIM
  when: ansible_os_family != "Solus"
  include: vim.yml

- name: Install VIM (Solus)
  when: ansible_os_family == "Solus"
  include: vim_solus.yml

- name: Create .vim directory
  file:
    path: "~/.vim/colors/"
    state: directory
