- name: Install fd, find replacement (Archlinux)
  when: ansible_os_family == "Archlinux"
  become: true
  package:
    state: present
    name: "fd"

- name: Configure alias
  lineinfile:
    create: true
    path: "~/.bash_aliases"
    line: "alias find='echo you should use fd instead'"
