- name: Download bat, cat replacement (Debian-based)
  when: ansible_os_family == "Debian"
  get_url:
    url: "https://github.com/sharkdp/bat/releases/download/v0.17.1/bat_0.17.1_amd64.deb"
    dest: "/tmp"
    checksum: "sha256:c02ca23add052009cde64746ff86e6da5765a89fd7494d380800250310180b23"

- name: Install bat (Debian)
  when: ansible_os_family == "Debian"
  become: true
  package:
    state: present
    deb: "/tmp/bat_0.17.1_amd64.deb"
