- name: Install bat, cat replacement (Debian)
  when: ansible_os_family == "Debian"
  become: true
  package:
    state: present
    deb: "https://github.com/sharkdp/bat/releases/download/v0.6.0/bat_0.6.0_amd64.deb"
