- name: Install Docker (Debian-based)
  when: ansible_os_family == "Debian"
  include: docker_debian.yml

- name: Install Docker (Arch-based)
  when: ansible_os_family == "Archlinux"
  include: docker_arch.yml

- name: Install Docker (Solus)
  when: ansible_os_family == "Solus"
  include: docker_solus.yml

- name: Configure alias
  lineinfile:
    create: true
    path: "~/.bash_aliases"
    line: "alias cat='bat'"
