- name: Install Bat (Debian-based)
  when: ansible_os_family == "Debian"
  include: bat_debian.yml

- name: Install Bat (Arch-based)
  when: ansible_os_family == "Archlinux"
  include: bat_arch.yml

- name: Install Bat (Solus)
  when: ansible_os_family == "Solus"
  include: bat_solus.yml

- name: Configure alias
  lineinfile:
    create: true
    path: "~/.bash_aliases"
    line: "alias cat='bat'"
